### ISSUE TITLE
Analytics, Sec-CH-UA-Next, additional fields

### ISSUE THREAD

**Issue by tresf** [WICG/ua-client-hints#111]
> Wouldn't it be nice if `User-Agent` was a (set of) client hints?

Assuming the User-Agent strings are eventually deprecated in favor of client hints, is it intended to be a full replacement for all User-Agent string information?  For example, as an ISV, I like to report on some of my own HTTP(S) requests for analytical purposes (anonymous usage data).

Some may ask why an app would use User-Agent strings for analytics and the answer is two fold:
* Some loadbalancers/appfirewalls/proxies outright block any "phone-home" requests without them, a robot-blocking security measure I guess
* In the age of vast, cheap CDNs, something as simple as a "is there an update to this software available" is often best (easiest?) served as an HTTP(S) request, snagging this anonymous data is convenient and often relevant.

So, let's say an app is written in Java, .NET, Python, these requests have a few choices... 
1. Don't send any user agent information (some environments will block; problems will occur)
2. Prepare a browser-like request, but with relevant data appended so proxy/webfirewall/admins have the information needed to adjust filters (how most are doing it now)
3. Make your own custom user-agent string that abides to no whitelisted standards, hope adjustment isn't too painful (I've noticed some out-of-the-box services don't like this)

With the addition of a new standard, it allows ISVs to stop mimicking historical decisions influenced by browsers.  As I'm writing this, I'm preparing something like the following:

```
Sec-CH-UA-Full-Version: 1.0.0
Sec-CH-UA-Platform-Version: 10.15.4
Sec-CH-UA: "My Custom App"; v="1.0.0"
Sec-CH-UA-Platform: macOS
Sec-CH-UA-Arch: x86_64
```

... however, in my current User-Agent, I'm able to append additional data... 

e.g.

```
User-Agent: Mozilla/5.0 (Macintosh; Mac OS X 10_15_4; x86_64) MyCustomApp/1.0.0 DotNET/4.0.0
```

Assuming "DotNET/4.0.0" is made up information that only I would spew into a service only to recollect it, is this type of information at all intended to live in the Client-Hints standard?  I understand that this may be observed as abuse of an information channel, but for statistical purposes, some additional fields may be warranted and I fear that the deprecation of the former technique will remove the ability to collect more fine-grained data.

Assuming analytics platforms begin to strictly comply with Client Hints, any made-up fields that the developer creates are likely to go ignored, right?

P.S.  If I'm way off the mark, please let me know, I'm just trying to stay abreast of what's to eventually come. 🍻

**Comment by amtunlimited** [comment]
I can see four options off the top of my head:

1. You can probably just keep using the user agent header or now. Presumably because of the amount of web apps still using it and the ingrained nature of the header it's probably not going away for a while...

2. Add your app information to the brand list in `Sec-CH-UA`. Hopefully the goals of GREASEing and making a list discourage a whitelist of brand names, but if they don't you could always just lie. The spec builds in for the use of random items so proxys blocking on the grounds of an unrecognized item will have a bad time. It might look like the following:

```
Sec-CH-UA: "MyCustomApp";v="1.0.0", "DotNET";v="4.0.0"`
```

3. You could just make up a completely separate header. I would hope that proxys/firewalls don't just drop random headers, so you could just make a new `X-Software-Info` header and populate it with anything you want (within spec, of course).

4. You could put that information in the URL or the body of a POST request, like submitting a form with that information. 

I hope that helps.

**Comment by tresf** [comment]
> ```
> Sec-CH-UA: "MyCustomApp";v="1.0.0", "DotNET";v="4.0.0"
> ```

Thanks for this proposal.  It's actually much cleaner to implement code-wise than the existing User-Agent approaches.  I'll start down that road now until/unless another technique comes strongly recommended.

**Comment by amtunlimited** [comment]
Just had a random thought: the spec does *not* dictate that the version information in the brand list must be a number (and the interface defines it as a DOMString), all of the examples seem to have a number.

**Comment by amtunlimited** [comment]
I'll go ahead and close this for now, but I can reopen if there are more questions

**Comment by tresf** [comment]
> Just had a random thought: the spec does not dictate that the version information in the brand list must be a number (and the interface defines it as a DOMString), all of the examples seem to have a number.

Snagged this from email (I think it was deleted afterwards), so keeping it here contextually.  What would a number look like?   Last I checked, the double-decimal breaks this.  Furthemore, semver has a better definition from a downstream perspective and contains stuff like "-RC", "+10", etc.  Sorry if I'm taking this off-topic, just wanted to complete the thought as I read it in email. :)

**Comment by amtunlimited** [comment]
A little of topic but happy to answer. The Client Hint HTTP headers (both request and response) are defined using [Structured Header](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html) formats. Specifically, the `Sec-CH-UA` header is defined as a [list](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#list) with each item having a "v" [parameter](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#param). In the examples, all of the "v" parameters look like [integers](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#integer) because they're supposed to be "major versions", which is an integer for most major browsers, but they all are surrounded by quotes which would make them [strings](https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#string). That would be in line with the [JS definition](https://wicg.github.io/ua-client-hints/#dom-navigatoruabrandversion-version) and would make sense because major versions don't *have* to be just an integer (they could be a codename or a major minor version with significant enough changes or a hash or whatever else the browser chooses), but is not explicitly stated that the "v" parameter should be a string.

But yes, I deleted it because it was off topic. :P 

I'll probably send a message or just whip up a small CL
