### ISSUE TITLE
If the browser refuses to send a hint (via HTTP), how can a site monitor that?

### ISSUE THREAD

**Issue by miketaylr** [WICG/ua-client-hints#208]
If the UA decides to not send a hint (for whatever policy reason), how should the site know that? Should we send back a value "rejected/denied/null" or similar?

**Comment by davidben** [comment]
Ideally, if reliability works out, the site can monitor that by way of it not being sent. (Early on we considered whether Critical-CH should be a signal like this that the site could react to, but we concluded a client-driven retry would be more robust, rather than risking buggy servers going into infinite loops.)

Beyond that, I suspect it'd depend on why it wasn't sent. If the policy reason was that some extension removed the header, then the header was removed and we probably wouldn't second-guess the extension with another value. If the policy reason was something like Privacy Budget, we can probably leave that to a broader Privacy-Budget-level reporting mechanism.

That might be simpler than having to augment every header with an extra `denied` token (which risks sites getting confused when parsing it).

**Comment by amtunlimited** [comment]
There's also the issue of non-supported hints. If we don't just drop them on the floor, we'd have to store them and send them back somehow, which would basically be a cookie with a couple of extra steps

**Comment by miketaylr** [comment]
> If the policy reason was something like Privacy Budget, we can probably leave that to a broader Privacy-Budget-level reporting mechanism.

Yeah, good point. User Agents may want to hook into the Reporting API, for various policy reasons (ITP, ETP, Privacy Budget) but until there's something more concrete to consider or interest by implementers I think we can just close this. 

If we decide it's useful later, we can define some reporting integration points similar to CSP, https://www.w3.org/TR/CSP3/#reporting
