### ISSUE TITLE
Clarify the meaning of 'network' 

### ISSUE THREAD

**Issue by miketaylr** [WICG/ua-client-hints#236]
In https://wicg.github.io/ua-client-hints/#fingerprinting:
> The primary goal of User Agent Client Hints is to reduce the default entropy available to the network for passive fingerprinting.

"Default entropy" and "network" might be slightly ambiguous here, so let's try to improve it.

**Comment by miketaylr** [comment]
(maybe ambiguous is the wrong word, unclear?)

My understanding of the terms:

default entropy - the bits of identifying information that could be used to create a fingerprint from the User-Agent string, which is sent by default for all requests

network - here we're referring to the HTTP layer, in particular the `User-Agent` header (see https://datatracker.ietf.org/doc/html/rfc7231#section-5.5.3) that is sent over HTTP(S)

Anybody have any suggested improvements to the wording here?

**Comment by ronancremin** [comment]
"Network" usually means a group of connected things. The phrase "available to the network" implies the ability to observe HTTP requests by elements in the network but in a HTTPS world only the destination server sees the contents of the request, so network doesn't feel like the right word when we're talking visibility of information for fingerprinting.  

I think that saying "HTTP layer" actually confuses things further since "layer" suggests the OSI network layer model in which HTTP is actually at the application layer. 

For consistency and alignment, why not use the term used in the HTTP protocol RFCs: "server" or "HTTP server"?

**Comment by miketaylr** [comment]
> "Network" usually means a group of connected things. The phrase "available to the network" implies the ability to observe HTTP requests by elements in the network but in a HTTPS world only the destination server sees the contents of the request, so network doesn't feel like the right word when we're talking visibility of information for fingerprinting.

That's fair. In my mind you have a 1st party site as the root node, and any 3rd party subresources as connected nodes that might also be capture this info. But I don't think it's crucial to capture the connected-ness. 

> For consistency and alignment, why not use the term used in the HTTP protocol RFCs: "server" or "HTTP server"?

"to a server" or "to servers" is a good suggestion. Want to send in a PR?

**Comment by ronancremin** [comment]
Will do.
