### ISSUE TITLE
Marketshare analysis only considers browsers and versions

### ISSUE THREAD

**Issue by jwrosewell** [WICG/ua-client-hints#269]
The current [draft of the document](https://wicg.github.io/ua-client-hints/#marketshare-analytics-use-case) does not consider marketshare analysis of device models, crawlers or operating systems.

**Comment by miketaylr** [comment]
I'm not sure about crawlers (because they may or may not support UA-CH?), but device models and OS analytics does seem useful to include.

@jwrosewell what about something like:

"For market share analytics to work, the server needs to be aware of the browser and its meaningful version, in order to be able to register them and find their relative market shares." => 

"For market share analytics to work, the server needs to be aware of the browser and its meaningful version, in order to be able to register them and find their relative market shares. Capturing device model and operating system may also be useful."

**Comment by miketaylr** [comment]
Something like that can work, thanks for the suggestion.

**Comment by miketaylr** [comment]
Fixed by https://github.com/WICG/ua-client-hints/commit/10bb1df4777962c39e77c9e8c054157bd56dbcdb
