### ISSUE TITLE
Regressive performance impact

### ISSUE THREAD

**Issue by AhsanE** [WICG/ua-client-hints#3]
My PWA has an average TTFB of 400ms worldwide. 

Depending on device name, I send resources conditionally i.e: latest devices get the cutting edge alpha features by default with option in setting to change it later.

How is it done? I have a database of tens of thousands of devices. They are grouped into different categories. i.e: High-end, Mid-tier, Low-end 
The categories are classified depending on the model name, model launch year. I.e: High-end device launched in 2017 is classified as a Upper-mid teir device in 2019. A device which is mid tier but performs like a high tier because of some specific quirks in hardware is defined as a high tier.

There are some exceptions here and there which I fix asap when I get a performance complaint.

Under the new expected model I've simulated the change, and this increases my TTFB from 400ms to over 1 second when accounting for interconnect uncertainty.

**Comment by ronancremin** [comment]
Ahsan is adding real life data to the point I was trying to make in https://github.com/WICG/ua-client-hints/issues/2. 

TBL et al had the foresight to include the User-Agent header in RFC1945 to help servers deliver the appropriate content to each client. One size does not fit all. Adding an additional round trip before the right content can be determined has real impact.

**Comment by yoavweiss** [comment]
I understand with the use-case, but requiring the sending of high-entropy data about our users by default in order to (in very few cases) generate a low-entropy decision from it (high, medium, low) doesn't seem tenable.

Using UA-CH, you can still access the device model, even if not at HTML generation time on very-first-view ([yet](https://github.com/WICG/client-hints-infrastructure/issues/16)). If you're interested in touching a lower number of entropy bits (which you should be), you can try to use the [Device Memory](https://w3c.github.io/device-memory/) API to act as a proxy for the tiers of device models. At last year's WebPerfWG F2F we also discussed a [CPU reporting API](https://blog.yoav.ws/webperfwg_f2f_2019/#cpu-reporting), which could've been helpful here.

**Comment by yoavweiss** [comment]
Closing as this is not actionable, but feel free to re-open if you feel this requires further discussion
