### ISSUE TITLE
Support for Chrome on iOS

### ISSUE THREAD

**Issue by christiancocking-foxadtech** [WICG/ua-client-hints#337]
Hello,

We are preparing to support User Agent Client hints as our sites do heavily depend on the granular User Agent data for a variety of requests out to our advertising partners.

In testing, we have noticed that on iOS based devices the client hints are not supported. It was also interesting to note that "Chrome on iOS" is not in the device support table here:

https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API

Is this expected that Chrome on iOS shouldn't pass forward values. 

PS: We are setting our response headers to ensure that the Client Hints are forwarded along to the various third parties that require the data.

**Comment by miketaylr** [comment]
(this is a Chrome-specific issue, rather than a spec one, but happy to answer) 

Unfortunately for non-Safari iOS browsers (include Chrome on iOS), WebKit will need to add support for User-Agent Client Hints before they can be enabled (because they control the network stack). 

The relevant standards issue for the WebKit project is over here: https://github.com/WebKit/standards-positions/issues/70, in case you would like to follow along.
