### ISSUE TITLE
Need a note regarding the tradeoff between GREASE and variance

### ISSUE THREAD

**Issue by yoavweiss** [WICG/ua-client-hints#44]
GREASEing the UA string has several tradeoffs when it comes to caching of adapted responses. We should recognize that and provide implementers with guidance.

/cc @jridgewell

**Comment by jridgewell** [comment]
Yup. So my hope is that we can reduce the entropy enough that the Request Headers are usable for varying, but still prevent ossification.

A few things that I've thought of:

## Compile-Time GREASE Randomness Only

Eg, at compile time, Chrome 81 generates the grease value "FooBar 21". Additionally the random ordering is chosen, let's say "first".

So, when Chrome send the non-grease header, it sends `Sec-CH-UA: Chrome 81`. And when it sends the grease header, it sends `Sec-CH-UA: FooBar 21, Chrome 81`. These could be the only two header values sent by Chrome 81.

Chrome 82, however, is a different compilation, had generates different grease values. Eg, it either sends `Sec-CH-UA: Chrome 82`, or `Sec-CH-UA: Chrome 82, BazQux 3`, and nothing else.

This effectively means that each browser would take 2 variations, but that's considerably better than an unbounded number. And it still could prevent ossification, since Chrome 82's UA could be significantly different than Chrome 81's.

## Only Using GREASEd Header

Meaning, Chrome 81 never sends `Sec-CH-UA: Chrome 81`. It can only send `Sec-CH-UA: FooBar 21, Chrome 81`. Same for Chrome 82 only sending `Sec-CH-UA: Chrome 82, BazQux 3`.

Note that we'd still be sending junk values to servers, but we've now reduced from 2 variations to just 1. And we still prevent ossification, because each compilation would be sending their own unique junk values.

**Comment by amtunlimited** [comment]
> Only Using GREASEd Header

When would we send the non-greased version? I would assume that if we send it once we would send it everywhere. 

We could randomly decide when to send it, and make it more frequent on sites we know are blacklisting in a bad way...

> Compile-Time GREASE Randomness Only

I like the idea of removing the tracking vector of randomness at compile time, but I wonder if that wouldn't lead to people just making tables of complete strings to brand and version. For example, someone would find `Sec-CH-UA: FooBar 21, Chrome 81` and immediately stick it in a table with "Chrome 81" next to it and negate the purpose of GREASE-ing

I suspect that it'd end up like the current "device detection" services that just have a big database of UA strings linked to device types and the like.

Also, it would need to only can on major version as opposed to *every* compile, as the other way would leak minor/bugfix versions for the same reason as above. I wonder how that would work out, infrastructure-wise...It wouldn't be impossible, just tricky
