### ISSUE TITLE
Request for some examples of how good bots would show up with this spec

### ISSUE THREAD

**Issue by ayumi-cloud** [WICG/ua-client-hints#50]
I've done a quick search to see if this was asked in the past and couldn't find an answer, so I've opened this issue.

Take the following example, GoogleBot:

Desktop example:

```
Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
```

Mobile example:

```
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z‡ Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
```

GoogleBot is a good example as they follow a lot of good practising and you can do reverse dns lookups to confirm.

Q1: What would GoogleBot's information look like with ua-client-hints ?

e.g. With the: The Sec-UA header field represents the user agent's **brand** and significant version. Plus the rest of this spec? I've only seen examples of real users and there's no examples of bots.

Q2: What would a fake GoogleBot look like with ua-client-hints ?

For example, the following ip address is currently spamming the internet trying to spoof GoogleBot:

```
IP address: 184.73.140.53
Reverse DNS: Amazon (not Google)
User-Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
```

![image](https://user-images.githubusercontent.com/57409060/73185089-5b4b4680-4115-11ea-8a5f-c1d46c42f58d.png)

I know WICG is NOT Google! I just want to know how this spec deals with search engine and good bot crawlers and what you they would look like? - For beta-testing purposes with this spec.

Q3: Maybe this spec could also update the `reverse dns` feature as well, to help people confirm if these bots are real or fake, e.g.

```
Sec-CH-UA-DNS: Google LLC.
```

Above indicates a real GoogleBot.

```
Sec-CH-UA-DNS: Amazon.
```

Above indicates a fake GoogleBot.

- Can use `Sec-CH-UA-DNS` to compare if the ip address is trying to use the name GoogleBot, for example.

**Comment by amtunlimited** [comment]
> Q1: What would GoogleBot's information look like with ua-client-hints ?

In general, the parts of the UA client hint set are supposed to match their equivalent parts in the UA strings, so a well-behaved Googlebot would probably send this:
```
Sec-CH-UA: Googlebot; v=2
```
As the rest of the information isn't added, so the other headers would presumably not be sent or would be empty if they are sent (except for maybe the `Sec-CH-UA-Mobile` header, as it seems to have two different bots).

As for all of the other information in the mobile UA example, I would be interested to know if the bot is actually run on some sort of emulation or if all of that is there because of the multitude of sites that do "device-detection" UA-sniffing and fail on a unrecognized UA string. Time will tell if that would still be necessary in a post-UA-CH world, but I hope not.

> Q2: What would a fake GoogleBot look like with ua-client-hints ?

Unfortunately specs cannot prevent a bad actor from lying, so it would probably still look the same. The spec does not, however, change how an IP address is sent with the requests, so any reverse-dns-based measures you have now should continue to work as expected.

**Comment by ayumi-cloud** [comment]
@amtunlimited  thank you 👍

**Comment by yoavweiss** [comment]
Closing as I believe the question was answered, but feel free to reopen.
