### ISSUE TITLE
Sec-CH-UA-Model client hint exposes info that is not currently exposed in Use-Agent or otherwise

### ISSUE THREAD

**Issue by othermaciej** [WICG/ua-client-hints#57]
Sec-CH-UA-Model client hint exposes info that is not currently exposed in User-Agent or otherwise, thus increasing available entropy. The use case is not explained in the spec and is non-obvious.

**Comment by Steve51D** [comment]
This is partially true.
The majority of User-Agents from mobile devices do currently expose the model. Just in a non-obvious form.

The primary exception to this is Apple. Safari does not expose the model at all and sometimes actively pretends to not even be a mobile device (e.g. using desktop mode means a Mac User-Agent is supplied instead of iPhone or iPad).

There are many cases where the remote host may want to know the model of the device. The main ones that come to mind are analytics and advertising.
Additionally, there are less high-profile use-cases such as making use of hardware that is only available on some devices. 
Yes, feature detection is sometimes a better route but in other cases an up-front check that can be performed on the server will be preferable to waiting for the client device to download and execute JavaScript. This is doubly true in the patchier mobile networks of developing counties.

**Comment by amtunlimited** [comment]
In Chrome for Android (and older versions of Chrome for iOS and other mobile browsers) is model is present. For example, this is my phone:

![Screenshot_20200205-172154~2](https://user-images.githubusercontent.com/1744426/73889128-f2627d80-483c-11ea-90bb-5085bd19a291.png)

The underlined portion says Pixel 3 XL, which is the phone I am currently typing on.

In the current implementation in Chrome, this header is left blank for desktop. It does not show any information was not already available in the UA string.

**Comment by othermaciej** [comment]
> In the current implementation in Chrome, this header is left blank for desktop. It does not show any information was not already available in the UA string.

Can the spec make clear that it's allowed to be blank? Perhaps even define it to be blank for non-Mobile platforms and optionally blank for Mobile?

**Comment by yoavweiss** [comment]
> Can the spec make clear that it's allowed to be blank? Perhaps even define it to be blank for non-Mobile platforms and optionally blank for Mobile?

That seems reasonable.

**Comment by mcatanzaro** [comment]
IMO it's unlikely to cause problems as long as blank values are common. Knock on wood. :)

**Comment by amtunlimited** [comment]
> IMO it's unlikely to cause problems as long as blank values are common. Knock on wood. :)

FWIW, as far as I'm aware most, if not all, major browsers don't send any kind of "model" information on desktop. I'd assume it would be the same for client hints.

I actually don't know what it would even mean on desktop...

**Comment by othermaciej** [comment]
> I actually don't know what it would even mean on desktop...

Desktop computers also have models. For example I'm currently on a "MacBook Pro (16-inch, 2019)". But it's likely not good to expose these to the web.

**Comment by othermaciej** [comment]
For the record, I reviewed and confirmed that PR #90 addresses this issue.
