### ISSUE TITLE
Why so many headers, can this not just be a simple key=val space separated header?

### ISSUE THREAD

**Issue by nojvek** [WICG/ua-client-hints#93]
Basically User-Agent is terrible, I agree. But it was a simple implementaion, a single header gave you everything. Having multiple headers is also expensive on the wire.

As a developer this is all I care.

`UA: browser=chrome|firefox|edge|safari browser_ver=<number> os=<win|mac|linux|ios|android> os_ver=<number> is_mobile=<0|1> ...other key=val`

From the browser, I can decide what I want to be sending for privacy purposes.

The standard key names are standardized and hopefully browser vendors can keep it simple and useful.

**Comment by sgammon** [comment]
@nojvek technically because the headers won't change for client hints between calls within the scope of a single client, they will be sent once over each HTTP2 connection once, and elided with [HPACK header compression](https://blog.cloudflare.com/hpack-the-silent-killer-feature-of-http-2/) on subsequent calls

i imagine the authors want to define different headers as they go, in their domain specification areas of relevance, rather then define all-in-one standard as they did with CSP, which added some drag as it required batch review of the entire spec with all components, rather than one hint at a time.

also, in standards like CSP that provided these things in blocks, there was a semi-regular format for the `value` portion of `key=val` in the header, that may be harder to amend to client hints, which could alternatively enjoy the benefits of a full header to spec a complex hint in the future.

i don't actually know the answer though, i am just trying to be helpful.

**Comment by yoavweiss** [comment]
@sgammon makes a good point regarding header compression ensuring that these different headers don't consume significant extra bandwidth.

Beyond that, splitting the different values over different headers allows responses to adapt and `Vary` based on specific hints, without adding other values to their cache keys.
UA-CH follows a decision that was taken as part of [Client Hints](https://httpwg.org/http-extensions/client-hints.html) a long while ago on that front, due to those reasons.

**Comment by yoavweiss** [comment]
Closing as I believe the question was answered, but feel free to re-open (or ping me if you're lacking permissions to do so)
