### ISSUE TITLE
Is Sec-CH-UA-Mobile future proof?

### ISSUE THREAD

**Issue by pvorb** [WICG/ua-client-hints#94]
I'd like to question, if Sec-CH-UA-Mobile will stand the test of time. Since we're talking about HTTP headers, which will likely still be around in the next few decades, the distinction between mobile and not mobile might soon become irrelevant once a new type of devices comes up.

For example, there might soon be many VR/AR devices which could probably benefit from a mobile view, but ultimately are a new class of device.

So my suggestion would be to instead introduce a new header called `Sec-CH-UA-Device-Category` or similar. This could take arbitrary fixed set of allowed strings that can be extended over time.

**Comment by tommck** [comment]
I'm truly surprised they're choosing to have a device category of any kind.  having "mobile" versus "desktop" sites seems like a smell in general to me. Especially when you've got situations like using a Windows 10 touch screen "desktop" machine, which would benefit from the "mobile" stuff.

I would have thought that the Chrome folks would want to avoid pigeon holing instead of varying things by capability of the device

**Comment by yoavweiss** [comment]
This seems related to #43

**Comment by yoavweiss** [comment]
Thinking about this some more, I think it would be better to keep `Sec-CH-UA-Mobile` as is (as a 1:1 replacement for today's mobile signal in UA strings). 

Future enhancements to that could go as a separate hint (e.g. the one described in #43).

**Comment by yoavweiss** [comment]
Closing as I don't believe any further action is needed. Please let me know if this requires more discussion and I'll reopen.
